language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -x test"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r hello *
  - mkdir -p deploy
  - mv hello.zip deploy/hello.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-build-kindturtle4u
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip파일 접근을 private 으로
    local_dir: deploy #before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - kindturtle4u@gmail.com