version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
  - object: /
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 774

hooks:
  ApplicationStart:
    - location: deploy.sh
      time: 60
      runas: ec2-user
